### ISSUE TITLE
bad encoding on deb package file raise unicode exception

### ISSUE THREAD

**Issue by ftoledo** [ximion/appstream-dep11#24]
We have a weird package in own repo with encoding errors in debian/control file strings  (We know, this is a third party package that have only binary deb for this unfortunately and is not made from us)

http://repo-huayra.conectarigualdad.gob.ar/huayra/pool/non-free/s/sopi/sopi_3.0.0_amd64.deb

Running appstrem-dep11 on our repo, raise an unhandled exception when extract fields like Maintainer or Description from package data on **read_packages_dict_from_file** function .

I think that can be solved, if you can previous sanitanized/convert the string o just handle the exception.
Thanks!

```
def read_packages_dict_from_file(archive_root, suite, component, arch, with_description=False):
    source_path = archive_root + "/dists/%s/%s/binary-%s/Packages.gz" % (suite, component, arch)
        
    pkgl10n = dict()
    if with_description:
        l10n_en_source_path = archive_root + "/dists/%s/%s/i18n/Translation-en.bz2" % (suite, component)
        if os.path.exists(l10n_en_source_path):
            try:
                l10n_file = bz2.open(l10n_en_source_path, mode='rb')
                l10ntagf = TagFile(l10n_file)
                for section in l10ntagf:
                    pkgname = section.get('Package')
                    if not pkgname:
                        continue
                    pkgl10n[pkgname] = dict()
                    pkgl10n[pkgname]['C'] = section.get('Description-en')
                l10n_file.close()
            except Exception as e:
                log.warning("Could not use i18n file '{}': {}".format(l10n_en_source_path, str(e)))

    f = gzip.open(source_path, 'rb')
    tagf = TagFile(f)
    package_dict = dict()
    for section in tagf:
        pkg = Package(section['Package'], section['Version'], section['Architecture'])
        if not section.get('Filename'):
            print("Package %s-%s has no filename specified." % (pkg['name'], pkg['version']))
            continue
        pkg.filename = section['Filename']
        pkg.maintainer = section['Maintainer']    <<<<< CRASH HERE <<<<<

        if with_description:
            if pkgl10n.get(pkg.name):
                pkg.set_description('C', pkgl10n[pkg.name].get('C'))
            else:
               pkg.set_description('C', section.get('Description'))  <<<<< CRASH HERE <<<<<

        pkg2 = package_dict.get(pkg.name)
        if pkg2:
            compare = version_compare(pkg2.version, pkg.version)
            if compare >= 0:
                continue
        package_dict[pkg.name] = pkg
    f.close()

    return package_dict

```

```
2018-07-05 15:52:26,166 - INFO: Skipped sud/main/amd64, no new packages to process.
2018-07-05 15:52:26,258 - INFO: Skipped sud/main/i386, no new packages to process.
2018-07-05 15:52:26,259 - INFO: Completed metadata extraction for suite sud/main
2018-07-05 15:52:26,260 - INFO: Skipped sud/contrib/amd64, no new packages to process.
2018-07-05 15:52:26,260 - INFO: Skipped sud/contrib/i386, no new packages to process.
2018-07-05 15:52:26,260 - INFO: Completed metadata extraction for suite sud/contrib
2018-07-05 15:52:26,261 - INFO: Skipped sud/non-free/amd64, no new packages to process.
2018-07-05 15:52:26,264 - INFO: Skipped sud/non-free/i386, no new packages to process.
2018-07-05 15:52:26,264 - INFO: Completed metadata extraction for suite sud/non-free
2018-07-05 15:52:27,169 - INFO: Skipped sud-updates/main/amd64, no new packages to process.
2018-07-05 15:52:27,197 - INFO: Skipped sud-updates/main/i386, no new packages to process.
2018-07-05 15:52:27,197 - INFO: Completed metadata extraction for suite sud-updates/main
2018-07-05 15:52:27,198 - INFO: Skipped sud-updates/contrib/amd64, no new packages to process.
2018-07-05 15:52:27,198 - INFO: Skipped sud-updates/contrib/i386, no new packages to process.
2018-07-05 15:52:27,198 - INFO: Completed metadata extraction for suite sud-updates/contrib
2018-07-05 15:52:27,199 - INFO: Skipped sud-updates/non-free/amd64, no new packages to process.
2018-07-05 15:52:27,199 - INFO: Skipped sud-updates/non-free/i386, no new packages to process.
2018-07-05 15:52:27,199 - INFO: Completed metadata extraction for suite sud-updates/non-free
2018-07-05 15:52:28,174 - INFO: Skipped zonda/main/amd64, no new packages to process.
2018-07-05 15:52:28,272 - INFO: Skipped zonda/main/i386, no new packages to process.
2018-07-05 15:52:28,272 - INFO: Completed metadata extraction for suite zonda/main
2018-07-05 15:52:28,273 - INFO: Skipped zonda/contrib/amd64, no new packages to process.
2018-07-05 15:52:28,273 - INFO: Skipped zonda/contrib/i386, no new packages to process.
2018-07-05 15:52:28,273 - INFO: Completed metadata extraction for suite zonda/contrib
Traceback (most recent call last):
  File "/usr/local/bin/dep11-generator", line 11, in <module>
    load_entry_point('dep11==0.5', 'console_scripts', 'dep11-generator')()
  File "/usr/local/lib/python3.5/dist-packages/dep11-0.5-py3.5.egg/dep11/generator.py", line 458, in main
    gen.process_suite(params[1])
  File "/usr/local/lib/python3.5/dist-packages/dep11-0.5-py3.5.egg/dep11/generator.py", line 179, in process_suite
    pkglist = self._get_packages_for(suite_name, component, arch)
  File "/usr/local/lib/python3.5/dist-packages/dep11-0.5-py3.5.egg/dep11/generator.py", line 116, in _get_packages_for
    return read_packages_dict_from_file(self._archive_root, suite, component, arch, with_description=with_desc).values()
  File "/usr/local/lib/python3.5/dist-packages/dep11-0.5-py3.5.egg/dep11/package.py", line 126, in read_packages_dict_from_file
    pkg.maintainer = section['Maintainer']
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 26: invalid continuation byte

```

**Comment by ximion** [comment]
@ftoledo 
appstream-dep11 is an old and discontinued project, and we recommend using [appstream-generator](https://github.com/ximion/appstream-generator) now, which is not only much more up to date, but also a bit easier to use and much, much faster.
If you have issues with asgen, we could continue the discussion over there.
