### ISSUE TITLE
lmdb.ReadersFullError: mdb_txn_begin: MDB_READERS_FULL: Environment maxreaders limit reached

### ISSUE THREAD

**Issue by iainlane** [ximion/appstream-dep11#4]
In [this log](https://github.com/ximion/appstream-dep11/files/46434/28_1949.txt) I hit lmdb.ReadersFullError. The extractor kept on with the rest of the components (didn't crash for example, which is good), but the one it was in at the time was left incomplete.

Any ideas why this might have happened and if it can be avoided?

> 2015-11-28 22:37:41,288 - INFO: Processed: uck (xenial/all), found 1
> multiprocessing.pool.RemoteTraceback:
> """
> Traceback (most recent call last):
>   File "/usr/lib/python3.4/multiprocessing/pool.py", line 119, in worker
>     result = (True, func(_args, *_kwds))
>   File "/home/ubuntu/appstream/lib/python3.4/site-packages/dep11-0.2-py3.4.egg/dep11/generator.py", line 49, in extract_metadata
>     mde.reopen_cache()
>   File "/home/ubuntu/appstream/lib/python3.4/site-packages/dep11-0.2-py3.4.egg/dep11/extractor.py", line 88, in reopen_cache
>     self._dcache.reopen()
>   File "/home/ubuntu/appstream/lib/python3.4/site-packages/dep11-0.2-py3.4.egg/dep11/datacache.py", line 75, in reopen
>     self.open(self.cache_dir)
>   File "/home/ubuntu/appstream/lib/python3.4/site-packages/dep11-0.2-py3.4.egg/dep11/datacache.py", line 50, in open
>     self._dbenv = lmdb.open(cachedir, max_dbs=3, map_size=self._map_size)
> lmdb.ReadersFullError: mdb_txn_begin: MDB_READERS_FULL: Environment maxreaders limit reached
> """
> 
> The above exception was the direct cause of the following exception:
> 
> lmdb.ReadersFullError: mdb_txn_begin: MDB_READERS_FULL: Environment maxreaders limit reached
> 2015-11-28 22:37:41,289 - ERROR: mdb_txn_begin: MDB_READERS_FULL: Environment maxreaders limit reached
> 2015-11-28 22:37:48,744 - INFO: Completed metadata extraction for suite xenial/universe

(appstream)ubuntu@juju-canonistack-lcy01-machine-23:~/appstream-dep11$ git rev-parse HEAD
35082dadffbfb39e8c9e8faee7c42b56f5cdd750

**Comment by ximion** [comment]
That's a very strange issue... According to  http://symas.com/mdb/doc/group__mdb.html#gae687966c24b790630be2a41573fe40e2 , this issue happens if the maximum number of threads/reader slots for the environment is exceeded.
Since py-lmdb sets `MDB_NOTLS` unconditionally, the read slots are tied to the transactions done on the database - and those are short-lived and terminate quickly.
So, according to the docs, there are a lot of open reader transactions - and I currently have no idea why that happens.
It's also strange that the issue happened when reopening the database again in a subprocess (and not while requesting another read transaction).

My current guess is that this might be just another multiprocessing issue: The LMDB cache is opened again in each subprocess, but for some reason, some subprocess(es) don't destroy their DataCache and keep it open - that would explain why we exceed the limit after a while. Also, after the faulty process crashed, the LMDB objects got freed so reading the cache was possible again.

I'll try if I can reproduce this issue here somehow...

**Comment by ziyadm** [comment]
reviving this from a long time ago: @iainlane @ximion did you guys ever find out what happened here? (i'm seeing this same issue in my app)

**Comment by iainlane** [comment]
No, but it's no longer a problem for us because we stopped using appstream-dep11 when it was superseded by appstream-generator.

**Comment by ximion** [comment]
@ziyadm One notable thing though is that this error never happened in the new implementation, which is using the LMDB C interface directly.
So I guess this is something related to the Python module.
